### PR TITLE
Drop support for Python < 3.6

### PR DESCRIPTION
**Pull request by WhyNotHugo**

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Updated `pypy` to `pypy3`. CI is now green.

**Comment by untitaker** [comment]
I would not drop Py2. There is no maintenance effort and it just makes people's life harder at this point.

**Comment by WhyNotHugo** [comment]
> makes people's life harder at this point.

Users of EOL'd versions of Python already need to pin old versions of most dependencies anyway.

**Comment by untitaker** [comment]
That's true and I observed this firsthand. There's still no reason to drop Python 2 that would serve anyone.

**Pull request closed without merging**
